<?php

namespace App\Console\Commands;

use Illuminate\Console\GeneratorCommand;
use Symfony\Component\Console\Input\InputOption;

class CreateRepository extends GeneratorCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $name = 'make:repository';


    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new Repository class';


    protected $type = 'Repository';


    protected function buildClass($name)
    {
        return parent::buildClass($name); // TODO: Change the autogenerated stub
    }

    protected function getStub()
    {
        return __DIR__.'/repository.stub';
    }

    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace .'\Repositories';
    }

    protected function getPath($name)
    {
        return parent::getPath($name.'Repository'); // TODO: Change the autogenerated stub
    }


}
